export declare function isNumeric(value: any): boolean;
export declare function isNumber(num: any): boolean;
export declare function isDate(value: any): boolean;
export declare function isDateLike(value: any): value is Date | string;
export declare function isBoolean(value: any): value is boolean;
export declare function isBool(value: any): value is boolean;
export declare function Bool(value: any): value is boolean;
export declare function isBigInt(value: any): value is bigint;
export declare function isString(value: any): boolean;
export declare function stringNotEmpty(value: any): boolean;
export declare function stringEmpty(text: string): boolean;
export declare function strStartsWith(str: string, prefix: string): boolean;
export declare function strEndsWith(str: string, suffix: string): boolean;
export declare function strEnclosedWith(str: string, trm: string): boolean;
export declare function leadingTabs(input: string): number;
export declare function repeatStr(text: string, times: number): string;
export declare function hasUnescapedDoubleQuote(input: string): boolean;
export declare function hasUnescapedColon(input: string): boolean;
export declare function hasUnescapedSemicolon(input: string): boolean;
export declare function isSingleRowString(input: any): boolean;
export declare function hasLeadingEmptyRow(input: string): boolean;
export declare function removeLeadingEmptyRows(input: string): string;
export declare function replaceAll(str: string, search: string, replacement: string): string;
export declare function normalizeNewlines(input: string, newline?: "\n" | "\r\n"): string;
export declare function escapeDoubleQuotes(str: string): string;
export declare function escapeColonSemicolon(str: string): string;
export declare function isArray(value: unknown): boolean;
export declare function isJsonObject(value: unknown): value is Record<string, unknown>;
export declare function isPrimitive(input: any): boolean;
export declare function restoreEscapedNewlinesTabs(input: string): string;
export declare function splitByFirstColon(input: string): [key: string, value: string];
export declare function findFirstColon(input: string): number;
export declare function isOlitList(entry: string, intent?: number | null): boolean;
